### PR TITLE
Added defensive checks to prevent InvalidCastException

### PR DESCRIPTION
**Pull request by calvin-fisher**
This should prevent the errors on level load that people have been reporting:
http://steamcommunity.com/workshop/filedetails/discussion/816260433/1842367319520455984/?ctp=17

### CODE REVIEW

**Comment by calvin-fisher** [comment]
I re-compiled with these changes, dropped in the new .dll, and everything is now working again in the latest version of the game.

**Comment by calvin-fisher** [comment]
Actually, found a bug: 
`Simulation error: Array index is out of range.`

Happens in `TransportLine.GetNextStop` or `PassengerTrainAI.ArrivingToDestination`

**Comment by calvin-fisher** [comment]
Okay, there are two problems.  One: after, loading an existing game there are a bunch of `Array index is out of range` exceptions in `PassengerTrainAIDetour.StartPathFind` and `PassengerTrainAI.ArrivingToDestination` but they seem to go away.

The bigger problem is that metro trains don't spawn.  All other vehicle types are spawning normally.

**Comment by calvin-fisher** [comment]
This stops all the errors, but I can't figure out how to make trains spawn.  Is this mod still being maintained?

**Comment by andreharv** [comment]
Hey sorry for no responding sooner.  I was on a hiatus but I am back now.  Looks cool!  Thanks for your contribution!

**Comment by calvin-fisher** [comment]
No problem, I was mostly trying to fix the bugs after the last version of the game was released.  I couldn't figure it out, but BloodyPenguin fixed it pretty soon after.

**Pull request closed without merging**
